"""add register and confirmation

Revision ID: 0a368f9373e4
Revises: 79d325f17876
Create Date: 2016-04-07 12:01:35.374356

"""

# revision identifiers, used by Alembic.
revision = '0a368f9373e4'
down_revision = '79d325f17876'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
