"""update the user model

Revision ID: 79d325f17876
Revises: d17817e7ef53
Create Date: 2016-04-06 23:05:04.534897

"""

# revision identifiers, used by Alembic.
revision = '79d325f17876'
down_revision = 'd17817e7ef53'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
